<?php
require_once '../includes/db.php';
require_once '../includes/auth.php';

// Revert User Impersonation Action
if (isset($_GET['action']) && $_GET['action'] === 'revert_impersonate') {
    if (isset($_SESSION['superadmin_impersonator'])) {
        $orig = $_SESSION['superadmin_impersonator'];
        $_SESSION['user'] = $orig;
        unset($_SESSION['superadmin_impersonator']);
        
        // Log activity
        if ($pdo) {
            try {
                $stmt = $pdo->prepare("INSERT INTO activity_logs (user_id, action, module, table_name, details) VALUES (?, 'Revert Impersonation', 'Security', 'users', ?)");
                $stmt->execute([$orig['id'] ?? 1, "Returned back to SuperAdmin session"]);
            } catch (Exception $e) {}
        }
        header("Location: settings.php?tab=security");
        exit;
    }
}

enforce_page_access('settings.php');
$user = $_SESSION['user'] ?? null;
$role = $user['role'] ?? 'Cashier';

// SuperAdmin Check
$is_superadmin = ($role === 'SuperAdmin');

// Download Database Backup Action (SuperAdmin Only)
if (isset($_GET['action']) && $_GET['action'] === 'download_backup' && $is_superadmin && $pdo) {
    $tables = [];
    $stmt_tbl = $pdo->query("SHOW TABLES");
    while ($row = $stmt_tbl->fetch(PDO::FETCH_NUM)) {
        $tables[] = $row[0];
    }

    $sql_dump = "-- --------------------------------------------------------\n";
    $sql_dump .= "-- TechShop CMS Database Backup Dump\n";
    $sql_dump .= "-- Generated by SuperAdmin (Software Engineer) on " . date('Y-m-d H:i:s') . "\n";
    $sql_dump .= "-- --------------------------------------------------------\n\n";
    $sql_dump .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

    foreach ($tables as $t) {
        $stmt_cr = $pdo->query("SHOW CREATE TABLE `$t`");
        $create_row = $stmt_cr->fetch(PDO::FETCH_NUM);
        $sql_dump .= "\n-- Structure for table `$t`\n";
        $sql_dump .= "DROP TABLE IF EXISTS `$t`;\n";
        $sql_dump .= $create_row[1] . ";\n\n";

        $stmt_data = $pdo->query("SELECT * FROM `$t`");
        $rows = $stmt_data->fetchAll(PDO::FETCH_ASSOC);
        if (!empty($rows)) {
            $sql_dump .= "-- Dumping data for table `$t`\n";
            foreach ($rows as $r) {
                $cols = array_map(fn($c) => "`$c`", array_keys($r));
                $vals = array_map(function($v) use ($pdo) {
                    if (is_null($v)) return "NULL";
                    return $pdo->quote($v);
                }, array_values($r));
                $sql_dump .= "INSERT INTO `$t` (" . implode(', ', $cols) . ") VALUES (" . implode(', ', $vals) . ");\n";
            }
            $sql_dump .= "\n";
        }
    }

    $sql_dump .= "SET FOREIGN_KEY_CHECKS=1;\n";
    
    header('Content-Type: application/sql');
    header('Content-Disposition: attachment; filename="techshop_backup_' . date('Ymd_His') . '.sql"');
    header('Content-Length: ' . strlen($sql_dump));
    echo $sql_dump;
    exit;
}

$msg = '';
$msg_type = 'success';

// Default Master Registries
$default_currencies = [
    ['code' => 'LKR', 'name' => 'Sri Lankan Rupee', 'symbol' => 'Rs.', 'rate' => 1.0, 'status' => 'active'],
    ['code' => 'USD', 'name' => 'US Dollar', 'symbol' => '$', 'rate' => 310.0, 'status' => 'active'],
    ['code' => 'EUR', 'name' => 'Euro', 'symbol' => '€', 'rate' => 340.0, 'status' => 'active'],
    ['code' => 'GBP', 'name' => 'British Pound', 'symbol' => '£', 'rate' => 395.0, 'status' => 'active'],
    ['code' => 'INR', 'name' => 'Indian Rupee', 'symbol' => '₹', 'rate' => 3.7, 'status' => 'active']
];

$default_languages = [
    ['code' => 'en', 'name' => 'English', 'native' => 'English', 'status' => 'active'],
    ['code' => 'si', 'name' => 'Sinhala', 'native' => 'සිංහල', 'status' => 'active'],
    ['code' => 'ta', 'name' => 'Tamil', 'native' => 'தமிழ்', 'status' => 'active']
];

// Fetch current settings
$settings = [];
if ($pdo) {
    try {
        $stmt_s = $pdo->query("SELECT setting_key, setting_value FROM settings");
        while ($row = $stmt_s->fetch(PDO::FETCH_ASSOC)) {
            $settings[$row['setting_key']] = $row['setting_value'];
        }
    } catch (Exception $e) {}
}

$system_currencies = $default_currencies;
if (!empty($settings['supported_currencies_json'])) {
    $decoded_c = json_decode($settings['supported_currencies_json'], true);
    if (is_array($decoded_c)) $system_currencies = $decoded_c;
}

$system_languages = $default_languages;
if (!empty($settings['supported_languages_json'])) {
    $decoded_l = json_decode($settings['supported_languages_json'], true);
    if (is_array($decoded_l)) $system_languages = $decoded_l;
}

// Handle SuperAdmin Actions
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {
    $action = $_POST['action'];

    // 1. Save System Settings
    if ($action === 'save_settings' && $pdo) {
        try {
            $stmt = $pdo->prepare("INSERT INTO settings (setting_key, setting_value) VALUES (?, ?) ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)");
            
            if (isset($_POST['settings']) && is_array($_POST['settings'])) {
                foreach ($_POST['settings'] as $k => $v) {
                    $stmt->execute([$k, trim($v)]);
                }
            }

            // Feature flags toggles
            $flags = ['feature_multibranch', 'feature_repairs', 'feature_custom_pc', 'feature_serials', 'feature_rma', 'feature_accounting', 'feature_tracker', 'superadmin_shop_access', 'maintenance_mode', 'shop_disabled', 'app_debug'];
            foreach ($flags as $flg) {
                $val = isset($_POST['settings'][$flg]) ? '1' : '0';
                $stmt->execute([$flg, $val]);
            }

            $msg = "System configurations & feature flags updated successfully!";
        } catch (Exception $e) {
            $msg = "Error updating settings: " . safe_error_message($e);
            $msg_type = 'error';
        }
    }

    // 2. Add / Update Currency in Registry
    if ($action === 'add_currency' && $pdo) {
        try {
            $code = strtoupper(trim($_POST['code'] ?? ''));
            $name = trim($_POST['name'] ?? '');
            $symbol = trim($_POST['symbol'] ?? '');
            $rate = (float)($_POST['rate'] ?? 1.0);
            $status = $_POST['status'] ?? 'active';

            if (empty($code) || empty($symbol)) {
                throw new Exception("Currency code and symbol are required.");
            }

            // Check if exists or update
            $found = false;
            foreach ($system_currencies as &$curr) {
                if ($curr['code'] === $code) {
                    $curr['name'] = $name;
                    $curr['symbol'] = $symbol;
                    $curr['rate'] = $rate;
                    $curr['status'] = $status;
                    $found = true;
                    break;
                }
            }
            if (!$found) {
                $system_currencies[] = [
                    'code' => $code,
                    'name' => $name,
                    'symbol' => $symbol,
                    'rate' => $rate,
                    'status' => $status
                ];
            }

            $json_val = json_encode($system_currencies);
            $stmt = $pdo->prepare("INSERT INTO settings (setting_key, setting_value) VALUES ('supported_currencies_json', ?) ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)");
            $stmt->execute([$json_val]);

            $msg = "Currency $code successfully registered in System Master!";
        } catch (Exception $e) {
            $msg = safe_error_message($e);
            $msg_type = 'error';
        }
    }

    // 2b. Delete Currency from Master
    if ($action === 'delete_currency' && $pdo) {
        try {
            $code = strtoupper(trim($_POST['code'] ?? ''));
            if (empty($code)) throw new Exception("Currency code missing.");

            $system_currencies = array_values(array_filter($system_currencies, function($c) use ($code) {
                return $c['code'] !== $code;
            }));

            $json_val = json_encode($system_currencies);
            $stmt = $pdo->prepare("INSERT INTO settings (setting_key, setting_value) VALUES ('supported_currencies_json', ?) ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)");
            $stmt->execute([$json_val]);

            $msg = "Currency $code deleted successfully from System Master!";
        } catch (Exception $e) {
            $msg = safe_error_message($e);
            $msg_type = 'error';
        }
    }

    // 2c. Toggle Currency Status
    if ($action === 'toggle_currency_status' && $pdo) {
        try {
            $code = strtoupper(trim($_POST['code'] ?? ''));
            foreach ($system_currencies as &$c) {
                if ($c['code'] === $code) {
                    $c['status'] = ($c['status'] ?? 'active') === 'active' ? 'inactive' : 'active';
                    break;
                }
            }
            $json_val = json_encode($system_currencies);
            $stmt = $pdo->prepare("INSERT INTO settings (setting_key, setting_value) VALUES ('supported_currencies_json', ?) ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)");
            $stmt->execute([$json_val]);

            $msg = "Currency $code status toggled successfully!";
        } catch (Exception $e) {
            $msg = safe_error_message($e);
            $msg_type = 'error';
        }
    }

    // 3. Add / Update Language in Registry
    if ($action === 'add_language' && $pdo) {
        try {
            $code = strtolower(trim($_POST['code'] ?? ''));
            $name = trim($_POST['name'] ?? '');
            $native = trim($_POST['native'] ?? '');
            $status = $_POST['status'] ?? 'active';

            if (empty($code) || empty($name)) {
                throw new Exception("Language code and name are required.");
            }

            $found = false;
            foreach ($system_languages as &$lang) {
                if ($lang['code'] === $code) {
                    $lang['name'] = $name;
                    $lang['native'] = $native;
                    $lang['status'] = $status;
                    $found = true;
                    break;
                }
            }
            if (!$found) {
                $system_languages[] = [
                    'code' => $code,
                    'name' => $name,
                    'native' => $native,
                    'status' => $status
                ];
            }

            $json_val = json_encode($system_languages);
            $stmt = $pdo->prepare("INSERT INTO settings (setting_key, setting_value) VALUES ('supported_languages_json', ?) ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)");
            $stmt->execute([$json_val]);

            $msg = "Language $name ($code) successfully registered in System Master!";
        } catch (Exception $e) {
            $msg = safe_error_message($e);
            $msg_type = 'error';
        }
    }

    // 3b. Delete Language from Master
    if ($action === 'delete_language' && $pdo) {
        try {
            $code = strtolower(trim($_POST['code'] ?? ''));
            if (empty($code)) throw new Exception("Language code missing.");

            $system_languages = array_values(array_filter($system_languages, function($l) use ($code) {
                return $l['code'] !== $code;
            }));

            $json_val = json_encode($system_languages);
            $stmt = $pdo->prepare("INSERT INTO settings (setting_key, setting_value) VALUES ('supported_languages_json', ?) ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)");
            $stmt->execute([$json_val]);

            $msg = "Language $code deleted successfully from System Master!";
        } catch (Exception $e) {
            $msg = safe_error_message($e);
            $msg_type = 'error';
        }
    }

    // 3c. Toggle Language Status
    if ($action === 'toggle_language_status' && $pdo) {
        try {
            $code = strtolower(trim($_POST['code'] ?? ''));
            foreach ($system_languages as &$l) {
                if ($l['code'] === $code) {
                    $l['status'] = ($l['status'] ?? 'active') === 'active' ? 'inactive' : 'active';
                    break;
                }
            }
            $json_val = json_encode($system_languages);
            $stmt = $pdo->prepare("INSERT INTO settings (setting_key, setting_value) VALUES ('supported_languages_json', ?) ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)");
            $stmt->execute([$json_val]);

            $msg = "Language $code status toggled successfully!";
        } catch (Exception $e) {
            $msg = safe_error_message($e);
            $msg_type = 'error';
        }
    }

    // 4. User Impersonation (Log in as any user for developer debugging)
    if ($action === 'impersonate_user' && $pdo) {
        try {
            $target_id = (int)$_POST['target_user_id'];
            $stmt_u = $pdo->prepare("SELECT id, name, email, role FROM users WHERE id = ?");
            $stmt_u->execute([$target_id]);
            $target_user = $stmt_u->fetch(PDO::FETCH_ASSOC);

            if ($target_user) {
                $_SESSION['superadmin_impersonator'] = $_SESSION['user'];
                $_SESSION['user'] = $target_user;

                // Log impersonation
                try {
                    $stmt_log = $pdo->prepare("INSERT INTO activity_logs (user_id, action, module, table_name, details) VALUES (?, 'User Impersonation', 'Security', 'users', ?)");
                    $stmt_log->execute([$user['id'] ?? 1, "SuperAdmin impersonated {$target_user['name']} ({$target_user['role']}) for debugging"]);
                } catch (Exception $ex) {}

                header("Location: dashboard.php");
                exit;
            } else {
                throw new Exception("Target user not found.");
            }
        } catch (Exception $e) {
            $msg = "Error impersonating user: " . safe_error_message($e);
            $msg_type = 'error';
        }
    }

    // 5. Force Reset Password for Any Account
    if ($action === 'force_password_reset' && $pdo) {
        try {
            $target_id = (int)$_POST['target_user_id'];
            $new_pass = $_POST['new_password'] ?? 'password123';
            $hash = password_hash($new_pass, PASSWORD_BCRYPT);

            $stmt_p = $pdo->prepare("UPDATE users SET password = ? WHERE id = ?");
            $stmt_p->execute([$hash, $target_id]);

            $msg = "Password force reset completed for User ID #$target_id!";
        } catch (Exception $e) {
            $msg = "Error resetting password: " . safe_error_message($e);
            $msg_type = 'error';
        }
    }

    // 5b. Force Kill / Invalidate All Staff Sessions
    if ($action === 'kill_sessions' && $pdo) {
        try {
            $token = bin2hex(random_bytes(16));
            $stmt = $pdo->prepare("INSERT INTO settings (setting_key, setting_value) VALUES ('global_session_version', ?) ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)");
            $stmt->execute([$token]);
            $_SESSION['user_session_version'] = $token;

            $msg = "All other staff sessions have been successfully terminated!";
        } catch (Exception $e) {
            $msg = "Error resetting sessions: " . safe_error_message($e);
            $msg_type = 'error';
        }
    }

    // 6. Run Schema Migration & Self-Repair
    if ($action === 'run_migration' && $pdo) {
        try {
            require_once '../setup_full_system.php';
            $msg = "Database schema migration executed! All tables, columns, and indexes verified.";
        } catch (Throwable $e) {
            $msg = "Migration notice: " . safe_error_message($e);
            $msg_type = 'error';
        }
    }

    // 6b. Restore Database from SQL Backup Upload
    if ($action === 'restore_backup' && $pdo) {
        try {
            if (!isset($_FILES['sql_file']) || $_FILES['sql_file']['error'] !== UPLOAD_ERR_OK) {
                throw new Exception("Please select a valid SQL backup file (.sql).");
            }

            $upload = $_FILES['sql_file'];
            if (($upload['size'] ?? 0) < 1 || $upload['size'] > 25 * 1024 * 1024) {
                throw new InvalidArgumentException('The SQL backup must be between 1 byte and 25 MB.');
            }
            if (strtolower(pathinfo($upload['name'] ?? '', PATHINFO_EXTENSION)) !== 'sql') {
                throw new InvalidArgumentException('Only .sql backup files are accepted.');
            }

            $file_tmp = $upload['tmp_name'];
            $sql_content = file_get_contents($file_tmp);
            if ($sql_content === false || trim($sql_content) === '') {
                throw new Exception("The uploaded SQL file is empty.");
            }

            $pdo->exec("SET FOREIGN_KEY_CHECKS = 0;");
            $pdo->exec($sql_content);
            $pdo->exec("SET FOREIGN_KEY_CHECKS = 1;");

            $msg = "Database successfully restored from SQL backup file!";
        } catch (Exception $e) {
            $pdo->exec("SET FOREIGN_KEY_CHECKS = 1;");
            $msg = "Error restoring database: " . safe_error_message($e);
            $msg_type = 'error';
        }
    }

    // 7. Purge System Cache
    if ($action === 'purge_cache') {
        if (function_exists('opcache_reset')) {
            @opcache_reset();
        }
        $msg = "Application opcode cache, template buffers, and temporary session logs purged successfully!";
    }

    // 8. Flush Activity & Audit Logs
    if ($action === 'clear_logs' && $pdo) {
        try {
            $pdo->exec("TRUNCATE TABLE activity_logs");
            $msg = "All system activity logs and audit logs purged successfully!";
        } catch (Exception $e) {
            $msg = "Error clearing logs: " . safe_error_message($e);
            $msg_type = 'error';
        }
    }
}

function get_setting($key, $default = '') {
    global $settings;
    return htmlspecialchars($settings[$key] ?? $default);
}

function is_flag_enabled($key, $default = 1) {
    global $settings;
    if (!isset($settings[$key])) return $default;
    return $settings[$key] === '1' || $settings[$key] === 'true';
}

// Fetch all users for SuperAdmin impersonation dropdown
$all_users = [];
if ($pdo) {
    try {
        $all_users = $pdo->query("SELECT id, name, email, role, status FROM users ORDER BY id ASC")->fetchAll(PDO::FETCH_ASSOC);
    } catch (Exception $e) {}
}

// Active Tab
$tab = $_GET['tab'] ?? 'system';

require_once '../includes/header.php';
?>

<div class="space-y-6 max-w-7xl mx-auto pb-12">
    
    <!-- Top Action Header -->
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
            <div class="flex items-center gap-2 mb-1">
                <span class="px-2.5 py-0.5 rounded-full bg-purple-100 text-purple-800 text-[11px] font-extrabold tracking-wider uppercase">
                    <i class="fa-solid fa-code mr-1"></i> Software Engineer Control Plane
                </span>
            </div>
            <h1 class="text-2xl font-bold text-slate-900 tracking-tight flex items-center gap-2.5">
                <i class="fa-solid fa-gears text-purple-600"></i>
                <span>SuperAdmin System & Infrastructure Settings</span>
            </h1>
            <p class="text-xs sm:text-sm text-slate-500 mt-0.5">Application environment, database management, API keys, user impersonation, currencies & language master registries.</p>
        </div>
        
        <div class="flex items-center gap-2.5">
            <a href="shop_settings.php" class="px-4 py-2.5 rounded-2xl bg-white border border-slate-200 text-slate-700 hover:bg-slate-50 text-xs sm:text-sm font-bold transition-all shadow-sm flex items-center gap-2">
                <i class="fa-solid fa-store text-emerald-600"></i>
                <span>Open Shop Settings</span>
            </a>
            <a href="settings.php?action=download_backup" class="px-4 py-2.5 rounded-2xl bg-blue-600 hover:bg-blue-700 text-white text-xs sm:text-sm font-bold transition-all shadow-sm shadow-blue-600/20 flex items-center gap-2">
                <i class="fa-solid fa-database text-xs"></i>
                <span>Download SQL Backup</span>
            </a>
        </div>
    </div>

    <?php if ($msg): ?>
        <div class="<?php echo $msg_type === 'success' ? 'bg-emerald-50 border-emerald-200 text-emerald-800' : 'bg-red-50 border-red-200 text-red-800'; ?> border px-4 py-3 rounded-2xl text-xs sm:text-sm flex items-center justify-between shadow-sm">
            <div class="flex items-center gap-2">
                <i class="fa-solid <?php echo $msg_type === 'success' ? 'fa-circle-check text-emerald-600' : 'fa-circle-exclamation text-red-600'; ?>"></i>
                <span><?php echo htmlspecialchars($msg); ?></span>
            </div>
        </div>
    <?php endif; ?>

    <!-- Navigation Tabs -->
    <div class="flex items-center gap-2 overflow-x-auto pb-1 border-b border-slate-200/80">
        <a href="settings.php?tab=system" class="px-4 py-2.5 rounded-2xl font-bold text-xs sm:text-sm transition-all whitespace-nowrap <?php echo $tab === 'system' ? 'bg-purple-600 text-white shadow-sm shadow-purple-600/20' : 'text-slate-600 hover:bg-slate-100'; ?>">
            <i class="fa-solid fa-server mr-1.5"></i> System & APIs
        </a>
        <a href="settings.php?tab=currencies" class="px-4 py-2.5 rounded-2xl font-bold text-xs sm:text-sm transition-all whitespace-nowrap <?php echo $tab === 'currencies' ? 'bg-purple-600 text-white shadow-sm shadow-purple-600/20' : 'text-slate-600 hover:bg-slate-100'; ?>">
            <i class="fa-solid fa-coins mr-1.5"></i> System Currencies
        </a>
        <a href="settings.php?tab=languages" class="px-4 py-2.5 rounded-2xl font-bold text-xs sm:text-sm transition-all whitespace-nowrap <?php echo $tab === 'languages' ? 'bg-purple-600 text-white shadow-sm shadow-purple-600/20' : 'text-slate-600 hover:bg-slate-100'; ?>">
            <i class="fa-solid fa-language mr-1.5"></i> System Languages
        </a>
        <a href="settings.php?tab=security" class="px-4 py-2.5 rounded-2xl font-bold text-xs sm:text-sm transition-all whitespace-nowrap <?php echo $tab === 'security' ? 'bg-purple-600 text-white shadow-sm shadow-purple-600/20' : 'text-slate-600 hover:bg-slate-100'; ?>">
            <i class="fa-solid fa-user-secret mr-1.5"></i> Security & Impersonation
        </a>
        <a href="settings.php?tab=backups" class="px-4 py-2.5 rounded-2xl font-bold text-xs sm:text-sm transition-all whitespace-nowrap <?php echo $tab === 'backups' ? 'bg-purple-600 text-white shadow-sm shadow-purple-600/20' : 'text-slate-600 hover:bg-slate-100'; ?>">
            <i class="fa-solid fa-database mr-1.5"></i> Database & Backups
        </a>
        <a href="settings.php?tab=diagnostics" class="px-4 py-2.5 rounded-2xl font-bold text-xs sm:text-sm transition-all whitespace-nowrap <?php echo $tab === 'diagnostics' ? 'bg-purple-600 text-white shadow-sm shadow-purple-600/20' : 'text-slate-600 hover:bg-slate-100'; ?>">
            <i class="fa-solid fa-heart-pulse mr-1.5"></i> Diagnostics & Logs
        </a>
    </div>

    <?php if ($tab === 'system'): ?>
    <!-- Tab 1: System, Environment & APIs -->
    <form method="POST" action="settings.php" class="space-y-6">
        <input type="hidden" name="action" value="save_settings">

        <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
            
            <!-- Column 1: Core System Parameters -->
            <div class="lg:col-span-2 space-y-6">
                
                <div class="bg-white rounded-3xl shadow-card border border-slate-100/90 p-6 sm:p-7 space-y-4">
                    <h2 class="text-base font-bold text-slate-900 flex items-center gap-2">
                        <i class="fa-solid fa-desktop text-purple-600"></i> Application Environment & Defaults
                    </h2>
                    
                    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        <div>
                            <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">System Application Name</label>
                            <input type="text" name="settings[system_name]" value="<?php echo get_setting('system_name', 'TechShop'); ?>" class="w-full px-4 py-2.5 bg-slate-50 border border-slate-200/80 rounded-2xl text-xs sm:text-sm font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-purple-500/20 focus:border-purple-500">
                        </div>

                        <div>
                            <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">System Timezone</label>
                            <select name="settings[system_timezone]" class="w-full px-4 py-2.5 bg-slate-50 border border-slate-200/80 rounded-2xl text-xs sm:text-sm font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-purple-500/20">
                                <?php 
                                $timezones = ['Asia/Colombo', 'UTC', 'America/New_York', 'America/Los_Angeles', 'Europe/London', 'Asia/Dubai', 'Asia/Singapore', 'Australia/Sydney'];
                                $curr_tz = get_setting('system_timezone', 'Asia/Colombo');
                                foreach ($timezones as $tz): ?>
                                    <option value="<?php echo $tz; ?>" <?php echo $curr_tz === $tz ? 'selected' : ''; ?>><?php echo $tz; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <!-- Maintenance Mode Control -->
                    <div class="p-5 bg-purple-50/60 rounded-3xl border border-purple-200/80 space-y-3" id="maintCard">
                        <div class="flex items-center justify-between">
                            <div>
                                <div class="flex items-center gap-2">
                                    <span class="font-bold text-slate-900 text-sm">System Maintenance Mode</span>
                                    <span id="maintBadge" class="px-2 py-0.5 rounded-full text-[10px] font-extrabold uppercase <?php echo is_flag_enabled('maintenance_mode', 0) ? 'bg-purple-200 text-purple-800 animate-pulse' : 'bg-slate-200 text-slate-600'; ?>">
                                        <?php echo is_flag_enabled('maintenance_mode', 0) ? 'Active (Locked)' : 'Disabled (Normal)'; ?>
                                    </span>
                                </div>
                                <span class="text-xs text-slate-500 block mt-0.5">Locks out shop owners, cashiers, technicians, and all non-SuperAdmin staff during upgrades.</span>
                            </div>
                            <label class="relative inline-flex items-center cursor-pointer">
                                <input type="checkbox" name="settings[maintenance_mode]" value="1" <?php echo is_flag_enabled('maintenance_mode', 0) ? 'checked' : ''; ?> onchange="quickLiveToggle('maintenance_mode', this.checked, this, 'maintBadge', 'Active (Locked)', 'Disabled (Normal)')" class="sr-only peer">
                                <div class="w-11 h-6 bg-slate-200 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-purple-600"></div>
                            </label>
                        </div>
                        <div>
                            <label class="block text-[11px] font-bold text-slate-600 uppercase tracking-wider mb-1">Custom Maintenance Banner Notice (Live Auto-Save)</label>
                            <input type="text" name="settings[maintenance_message]" value="<?php echo get_setting('maintenance_message', 'The system is undergoing scheduled technical maintenance and upgrades. Please check back shortly.'); ?>" onchange="quickLiveTextUpdate('maintenance_message', this)" class="w-full px-3.5 py-2 bg-white border border-purple-200 rounded-xl text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-purple-500/20">
                        </div>
                    </div>

                    <!-- Shop Lockdown / Disable Shop Control -->
                    <div class="p-5 bg-red-50/60 rounded-3xl border border-red-200/80 space-y-3" id="shopLockCard">
                        <div class="flex items-center justify-between">
                            <div>
                                <div class="flex items-center gap-2">
                                    <span class="font-bold text-slate-900 text-sm">Disable Shop (Store Lockdown / Suspend Access)</span>
                                    <span id="shopLockBadge" class="px-2 py-0.5 rounded-full text-[10px] font-extrabold uppercase <?php echo is_flag_enabled('shop_disabled', 0) ? 'bg-red-200 text-red-800 animate-pulse' : 'bg-emerald-100 text-emerald-800'; ?>">
                                        <?php echo is_flag_enabled('shop_disabled', 0) ? 'Shop Suspended' : 'Shop Operational'; ?>
                                    </span>
                                </div>
                                <span class="text-xs text-slate-500 block mt-0.5">Completely disables store access for non-payment or store suspension. Only SuperAdmin can log in.</span>
                            </div>
                            <label class="relative inline-flex items-center cursor-pointer">
                                <input type="checkbox" name="settings[shop_disabled]" value="1" <?php echo is_flag_enabled('shop_disabled', 0) ? 'checked' : ''; ?> onchange="quickLiveToggle('shop_disabled', this.checked, this, 'shopLockBadge', 'Shop Suspended', 'Shop Operational')" class="sr-only peer">
                                <div class="w-11 h-6 bg-slate-200 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-red-600"></div>
                            </label>
                        </div>
                        <div>
                            <label class="block text-[11px] font-bold text-slate-600 uppercase tracking-wider mb-1">Shop Suspension / Deactivation Reason Notice (Live Auto-Save)</label>
                            <input type="text" name="settings[shop_disabled_message]" value="<?php echo get_setting('shop_disabled_message', 'This shop account has been deactivated or suspended by system administration. Please contact technical engineering support.'); ?>" onchange="quickLiveTextUpdate('shop_disabled_message', this)" class="w-full px-3.5 py-2 bg-white border border-red-200 rounded-xl text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-red-500/20">
                        </div>
                    </div>
                </div>

                <!-- API Keys & Integrations -->
                <div class="bg-white rounded-3xl shadow-card border border-slate-100/90 p-6 sm:p-7 space-y-4">
                    <h2 class="text-base font-bold text-slate-900 flex items-center gap-2">
                        <i class="fa-solid fa-plug text-purple-600"></i> API Integrations & Webhook Credentials
                    </h2>
                    
                    <div class="space-y-4">
                        <!-- SMS Gateway -->
                        <div class="p-4 bg-slate-50 rounded-2xl border border-slate-200/70 space-y-3">
                            <span class="text-xs font-bold text-slate-700 uppercase tracking-wider block">SMS Gateway (Twilio / NotifyLK / Vonage)</span>
                            <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
                                <div>
                                    <label class="block text-[11px] font-bold text-slate-600 mb-1">API Key / Account SID</label>
                                    <input type="text" name="settings[sms_api_key]" value="<?php echo get_setting('sms_api_key', 'AC_live_demo_key_89712'); ?>" class="w-full px-3 py-1.5 bg-white border border-slate-200 rounded-xl text-xs font-mono text-slate-800">
                                </div>
                                <div>
                                    <label class="block text-[11px] font-bold text-slate-600 mb-1">Auth Token / Secret</label>
                                    <input type="password" name="settings[sms_api_token]" value="<?php echo get_setting('sms_api_token', '••••••••••••••••'); ?>" class="w-full px-3 py-1.5 bg-white border border-slate-200 rounded-xl text-xs font-mono text-slate-800">
                                </div>
                            </div>
                        </div>

                        <!-- Email SMTP -->
                        <div class="p-4 bg-slate-50 rounded-2xl border border-slate-200/70 space-y-3">
                            <span class="text-xs font-bold text-slate-700 uppercase tracking-wider block">SMTP Mailer Settings</span>
                            <div class="grid grid-cols-1 sm:grid-cols-3 gap-3">
                                <div>
                                    <label class="block text-[11px] font-bold text-slate-600 mb-1">SMTP Host</label>
                                    <input type="text" name="settings[smtp_host]" value="<?php echo get_setting('smtp_host', 'smtp.gmail.com'); ?>" class="w-full px-3 py-1.5 bg-white border border-slate-200 rounded-xl text-xs font-mono text-slate-800">
                                </div>
                                <div>
                                    <label class="block text-[11px] font-bold text-slate-600 mb-1">SMTP Port</label>
                                    <input type="text" name="settings[smtp_port]" value="<?php echo get_setting('smtp_port', '587'); ?>" class="w-full px-3 py-1.5 bg-white border border-slate-200 rounded-xl text-xs font-mono text-slate-800">
                                </div>
                                <div>
                                    <label class="block text-[11px] font-bold text-slate-600 mb-1">Encryption</label>
                                    <select name="settings[smtp_crypto]" class="w-full px-3 py-1.5 bg-white border border-slate-200 rounded-xl text-xs font-bold text-slate-800">
                                        <option value="tls">TLS</option>
                                        <option value="ssl">SSL</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <!-- Column 2: Feature Flags & License -->
            <div class="space-y-6">
                
                <!-- Feature Flags -->
                <div class="bg-white rounded-3xl shadow-card border border-slate-100/90 p-6 sm:p-7 space-y-4">
                    <div class="flex items-center justify-between">
                        <h2 class="text-base font-bold text-slate-900 flex items-center gap-2">
                            <i class="fa-solid fa-toggle-on text-purple-600"></i> Module Feature Flags
                        </h2>
                        <span class="text-[10px] font-bold text-purple-600 bg-purple-50 px-2 py-0.5 rounded-full">Instant Live Update</span>
                    </div>
                    <p class="text-xs text-slate-400">Toggling any switch instantly updates the system without page reload.</p>

                    <div class="space-y-3 pt-2">
                        <!-- SuperAdmin Developer Support Access Toggle -->
                        <label class="flex items-center justify-between p-3.5 rounded-2xl bg-purple-50/80 border border-purple-200/80 cursor-pointer hover:bg-purple-100/70 transition-colors">
                            <div>
                                <span class="text-xs font-bold text-purple-900 block">SuperAdmin Shop Access (Support / Debug Mode)</span>
                                <span class="text-[11px] text-purple-600">Enable only when error handling or troubleshooting shop pages.</span>
                            </div>
                            <input type="checkbox" name="settings[superadmin_shop_access]" value="1" <?php echo is_flag_enabled('superadmin_shop_access', 0) ? 'checked' : ''; ?> onchange="quickLiveToggle('superadmin_shop_access', this.checked, this)" class="w-4 h-4 text-purple-600 rounded">
                        </label>
                        <label class="flex items-center justify-between p-3 rounded-2xl bg-slate-50 border border-slate-200/70 cursor-pointer hover:bg-slate-100/70 transition-colors">
                            <span class="text-xs font-bold text-slate-800">Repair & Service Jobs Workbench</span>
                            <input type="checkbox" name="settings[feature_repairs]" value="1" <?php echo is_flag_enabled('feature_repairs', 1) ? 'checked' : ''; ?> onchange="quickLiveToggle('feature_repairs', this.checked, this)" class="w-4 h-4 text-purple-600 rounded">
                        </label>
                        <label class="flex items-center justify-between p-3 rounded-2xl bg-slate-50 border border-slate-200/70 cursor-pointer hover:bg-slate-100/70 transition-colors">
                            <span class="text-xs font-bold text-slate-800">Hardware Serial/IMEI Tracking</span>
                            <input type="checkbox" name="settings[feature_serials]" value="1" <?php echo is_flag_enabled('feature_serials', 1) ? 'checked' : ''; ?> onchange="quickLiveToggle('feature_serials', this.checked, this)" class="w-4 h-4 text-purple-600 rounded">
                        </label>

                        <label class="flex items-center justify-between p-3 rounded-2xl bg-slate-50 border border-slate-200/70 cursor-pointer hover:bg-slate-100/70 transition-colors">
                            <span class="text-xs font-bold text-slate-800">Custom PC Builder Module</span>
                            <input type="checkbox" name="settings[feature_custom_pc]" value="1" <?php echo is_flag_enabled('feature_custom_pc', 1) ? 'checked' : ''; ?> onchange="quickLiveToggle('feature_custom_pc', this.checked, this)" class="w-4 h-4 text-purple-600 rounded">
                        </label>

                        <label class="flex items-center justify-between p-3 rounded-2xl bg-slate-50 border border-slate-200/70 cursor-pointer hover:bg-slate-100/70 transition-colors">
                            <span class="text-xs font-bold text-slate-800">Multi-Branch Network</span>
                            <input type="checkbox" name="settings[feature_multibranch]" value="1" <?php echo is_flag_enabled('feature_multibranch', 1) ? 'checked' : ''; ?> onchange="quickLiveToggle('feature_multibranch', this.checked, this)" class="w-4 h-4 text-purple-600 rounded">
                        </label>

                        <label class="flex items-center justify-between p-3 rounded-2xl bg-slate-50 border border-slate-200/70 cursor-pointer hover:bg-slate-100/70 transition-colors">
                            <span class="text-xs font-bold text-slate-800">Warranty Claims & RMA</span>
                            <input type="checkbox" name="settings[feature_rma]" value="1" <?php echo is_flag_enabled('feature_rma', 1) ? 'checked' : ''; ?> onchange="quickLiveToggle('feature_rma', this.checked, this)" class="w-4 h-4 text-purple-600 rounded">
                        </label>

                        <label class="flex items-center justify-between p-3 rounded-2xl bg-slate-50 border border-slate-200/70 cursor-pointer hover:bg-slate-100/70 transition-colors">
                            <span class="text-xs font-bold text-slate-800">Daily Cash Drawer & Accounting</span>
                            <input type="checkbox" name="settings[feature_accounting]" value="1" <?php echo is_flag_enabled('feature_accounting', 1) ? 'checked' : ''; ?> onchange="quickLiveToggle('feature_accounting', this.checked, this)" class="w-4 h-4 text-purple-600 rounded">
                        </label>

                        <label class="flex items-center justify-between p-3 rounded-2xl bg-slate-50 border border-slate-200/70 cursor-pointer hover:bg-slate-100/70 transition-colors">
                            <span class="text-xs font-bold text-slate-800">Public Repair QR Tracker</span>
                            <input type="checkbox" name="settings[feature_tracker]" value="1" <?php echo is_flag_enabled('feature_tracker', 1) ? 'checked' : ''; ?> onchange="quickLiveToggle('feature_tracker', this.checked, this)" class="w-4 h-4 text-purple-600 rounded">
                        </label>
                    </div>
                </div>

                <!-- License & Version -->
                <div class="bg-slate-900 rounded-3xl p-6 text-white space-y-3">
                    <div class="flex items-center justify-between">
                        <span class="text-[10px] uppercase font-bold text-purple-400 tracking-wider">License Status</span>
                        <span class="px-2 py-0.5 rounded-lg bg-emerald-500/20 text-emerald-400 font-bold text-[10px]">Enterprise Developer</span>
                    </div>
                    <h3 class="text-base font-bold">TechShop CMS v2.6.0 Pro</h3>
                    <p class="text-xs text-slate-400 font-mono">Engineered for High-Throughput Retail & Computer Repair Operations.</p>
                </div>

            </div>

        </div>

        <div class="flex justify-end">
            <button type="submit" class="px-7 py-3 rounded-2xl bg-purple-600 hover:bg-purple-700 text-white font-bold text-xs sm:text-sm transition-all shadow-sm shadow-purple-600/25">
                Save System Configurations
            </button>
        </div>
    </form>
    <?php endif; ?>

    <?php if ($tab === 'currencies'): ?>
    <!-- Tab 2: System Currencies Master -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        <!-- Add / Edit Currency Form -->
        <div class="bg-white rounded-3xl shadow-card border border-slate-100/90 p-6 sm:p-7 space-y-4">
            <h2 class="text-base font-bold text-slate-900 flex items-center gap-2">
                <i class="fa-solid fa-plus-circle text-purple-600"></i> Register System Currency
            </h2>
            <p class="text-xs text-slate-400">Currencies registered here become available for Shop Owners to select as their operating currency.</p>

            <form method="POST" action="settings.php?tab=currencies" class="space-y-4 pt-2">
                <input type="hidden" name="action" value="add_currency">

                <div>
                    <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">Currency Code (ISO 3-Letter) *</label>
                    <input type="text" name="code" required placeholder="e.g. AUD" maxlength="5" class="w-full px-4 py-2.5 bg-slate-50 border border-slate-200/80 rounded-2xl text-xs sm:text-sm font-bold uppercase text-slate-800">
                </div>

                <div>
                    <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">Currency Name *</label>
                    <input type="text" name="name" required placeholder="e.g. Australian Dollar" class="w-full px-4 py-2.5 bg-slate-50 border border-slate-200/80 rounded-2xl text-xs sm:text-sm text-slate-800">
                </div>

                <div class="grid grid-cols-2 gap-3">
                    <div>
                        <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">Symbol *</label>
                        <input type="text" name="symbol" required placeholder="e.g. A$" class="w-full px-4 py-2.5 bg-slate-50 border border-slate-200/80 rounded-2xl text-xs sm:text-sm font-bold text-slate-800">
                    </div>
                    <div>
                        <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">Base Rate</label>
                        <input type="number" step="0.0001" name="rate" value="1.0" class="w-full px-4 py-2.5 bg-slate-50 border border-slate-200/80 rounded-2xl text-xs sm:text-sm font-bold text-slate-800">
                    </div>
                </div>

                <div>
                    <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">Status</label>
                    <select name="status" class="w-full px-4 py-2.5 bg-slate-50 border border-slate-200/80 rounded-2xl text-xs sm:text-sm font-bold text-slate-800">
                        <option value="active">Active (Available to Shops)</option>
                        <option value="inactive">Inactive</option>
                    </select>
                </div>

                <button type="submit" class="w-full py-3 bg-purple-600 hover:bg-purple-700 text-white font-bold text-xs sm:text-sm rounded-2xl transition-all shadow-sm shadow-purple-600/25">
                    Save to Currency Master
                </button>
            </form>
        </div>

        <!-- Currencies List -->
        <div class="lg:col-span-2 bg-white rounded-3xl shadow-card border border-slate-100/90 p-6 sm:p-7 space-y-4">
            <div class="flex items-center justify-between">
                <h2 class="text-base font-bold text-slate-900 flex items-center gap-2">
                    <i class="fa-solid fa-coins text-purple-600"></i> Supported System Currencies (<?php echo count($system_currencies); ?>)
                </h2>
                <span class="text-xs text-slate-400 font-medium">Click Edit to modify or Delete to remove</span>
            </div>

            <div class="overflow-x-auto">
                <table class="w-full text-left text-xs border-collapse">
                    <thead>
                        <tr class="bg-slate-50 border-b border-slate-200 text-slate-700 font-bold uppercase text-[11px]">
                            <th class="py-3 px-4">Code</th>
                            <th class="py-3 px-4">Currency Name</th>
                            <th class="py-3 px-4">Symbol</th>
                            <th class="py-3 px-4 text-center">Exchange Rate</th>
                            <th class="py-3 px-4 text-center">Status</th>
                            <th class="py-3 px-4 text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-slate-100">
                        <?php foreach ($system_currencies as $c): ?>
                        <tr class="hover:bg-slate-50/60 transition-colors">
                            <td class="py-3.5 px-4 font-bold font-mono text-purple-700"><?php echo htmlspecialchars($c['code']); ?></td>
                            <td class="py-3.5 px-4 font-semibold text-slate-800"><?php echo htmlspecialchars($c['name']); ?></td>
                            <td class="py-3.5 px-4 font-bold text-slate-900"><?php echo htmlspecialchars($c['symbol']); ?></td>
                            <td class="py-3.5 px-4 text-center font-mono font-medium"><?php echo htmlspecialchars($c['rate'] ?? '1.0'); ?></td>
                            <td class="py-3.5 px-4 text-center">
                                <form method="POST" action="settings.php?tab=currencies" class="inline-block">
                                    <input type="hidden" name="action" value="toggle_currency_status">
                                    <input type="hidden" name="code" value="<?php echo htmlspecialchars($c['code']); ?>">
                                    <button type="submit" title="Click to toggle status" class="px-2.5 py-0.5 rounded-full text-[10px] font-extrabold uppercase transition-all <?php echo ($c['status'] ?? 'active') === 'active' ? 'bg-emerald-50 text-emerald-700 border border-emerald-200 hover:bg-emerald-100' : 'bg-slate-100 text-slate-500 hover:bg-slate-200'; ?>">
                                        <?php echo htmlspecialchars($c['status'] ?? 'active'); ?>
                                    </button>
                                </form>
                            </td>
                            <td class="py-3.5 px-4 text-right whitespace-nowrap">
                                <div class="flex items-center justify-end gap-1.5">
                                    <button type="button" onclick="editCurrency('<?php echo htmlspecialchars($c['code'], ENT_QUOTES); ?>', '<?php echo htmlspecialchars($c['name'], ENT_QUOTES); ?>', '<?php echo htmlspecialchars($c['symbol'], ENT_QUOTES); ?>', '<?php echo htmlspecialchars($c['rate'] ?? '1.0', ENT_QUOTES); ?>', '<?php echo htmlspecialchars($c['status'] ?? 'active', ENT_QUOTES); ?>')" class="p-1.5 text-purple-600 hover:bg-purple-50 rounded-lg text-xs font-semibold transition-colors" title="Edit Currency">
                                        <i class="fa-solid fa-pen-to-square"></i>
                                    </button>
                                    <form method="POST" action="settings.php?tab=currencies" class="inline-block" onsubmit="return confirm('Are you sure you want to delete currency <?php echo htmlspecialchars($c['code'], ENT_QUOTES); ?>?');">
                                        <input type="hidden" name="action" value="delete_currency">
                                        <input type="hidden" name="code" value="<?php echo htmlspecialchars($c['code']); ?>">
                                        <button type="submit" class="p-1.5 text-red-500 hover:bg-red-50 rounded-lg text-xs font-semibold transition-colors" title="Delete Currency">
                                            <i class="fa-solid fa-trash"></i>
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
    <?php endif; ?>

    <?php if ($tab === 'languages'): ?>
    <!-- Tab 3: System Languages Master -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        <!-- Add / Edit Language Form -->
        <div class="bg-white rounded-3xl shadow-card border border-slate-100/90 p-6 sm:p-7 space-y-4">
            <h2 class="text-base font-bold text-slate-900 flex items-center gap-2">
                <i class="fa-solid fa-plus-circle text-purple-600"></i> Register System Language
            </h2>
            <p class="text-xs text-slate-400">Languages registered here become selectable in Shop Settings for the user interface.</p>

            <form method="POST" action="settings.php?tab=languages" class="space-y-4 pt-2" id="langForm">
                <input type="hidden" name="action" value="add_language">

                <div>
                    <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">Language Code (ISO 639-1) *</label>
                    <input type="text" name="code" id="langCodeInput" required placeholder="e.g. ja" maxlength="5" class="w-full px-4 py-2.5 bg-slate-50 border border-slate-200/80 rounded-2xl text-xs sm:text-sm font-bold lowercase text-slate-800">
                </div>

                <div>
                    <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">English Name *</label>
                    <input type="text" name="name" id="langNameInput" required placeholder="e.g. Japanese" class="w-full px-4 py-2.5 bg-slate-50 border border-slate-200/80 rounded-2xl text-xs sm:text-sm text-slate-800">
                </div>

                <div>
                    <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">Native Script Label</label>
                    <input type="text" name="native" id="langNativeInput" placeholder="e.g. 日本語" class="w-full px-4 py-2.5 bg-slate-50 border border-slate-200/80 rounded-2xl text-xs sm:text-sm text-slate-800">
                </div>

                <div>
                    <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">Status</label>
                    <select name="status" id="langStatusInput" class="w-full px-4 py-2.5 bg-slate-50 border border-slate-200/80 rounded-2xl text-xs sm:text-sm font-bold text-slate-800">
                        <option value="active">Active (Available to Shops)</option>
                        <option value="inactive">Inactive</option>
                    </select>
                </div>

                <button type="submit" class="w-full py-3 bg-purple-600 hover:bg-purple-700 text-white font-bold text-xs sm:text-sm rounded-2xl transition-all shadow-sm shadow-purple-600/25">
                    Save to Language Master
                </button>
            </form>
        </div>

        <!-- Languages List -->
        <div class="lg:col-span-2 bg-white rounded-3xl shadow-card border border-slate-100/90 p-6 sm:p-7 space-y-4">
            <div class="flex items-center justify-between">
                <h2 class="text-base font-bold text-slate-900 flex items-center gap-2">
                    <i class="fa-solid fa-language text-purple-600"></i> Supported System Languages (<?php echo count($system_languages); ?>)
                </h2>
                <span class="text-xs text-slate-400 font-medium">Click Edit to modify or Delete to remove</span>
            </div>

            <div class="overflow-x-auto">
                <table class="w-full text-left text-xs border-collapse">
                    <thead>
                        <tr class="bg-slate-50 border-b border-slate-200 text-slate-700 font-bold uppercase text-[11px]">
                            <th class="py-3 px-4">Code</th>
                            <th class="py-3 px-4">English Name</th>
                            <th class="py-3 px-4">Native Script</th>
                            <th class="py-3 px-4 text-center">Status</th>
                            <th class="py-3 px-4 text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-slate-100">
                        <?php foreach ($system_languages as $l): ?>
                        <tr class="hover:bg-slate-50/60 transition-colors">
                            <td class="py-3.5 px-4 font-bold font-mono text-purple-700"><?php echo htmlspecialchars($l['code']); ?></td>
                            <td class="py-3.5 px-4 font-semibold text-slate-800"><?php echo htmlspecialchars($l['name']); ?></td>
                            <td class="py-3.5 px-4 font-bold text-slate-900"><?php echo htmlspecialchars($l['native'] ?? '-'); ?></td>
                            <td class="py-3.5 px-4 text-center">
                                <form method="POST" action="settings.php?tab=languages" class="inline-block">
                                    <input type="hidden" name="action" value="toggle_language_status">
                                    <input type="hidden" name="code" value="<?php echo htmlspecialchars($l['code']); ?>">
                                    <button type="submit" title="Click to toggle status" class="px-2.5 py-0.5 rounded-full text-[10px] font-extrabold uppercase transition-all <?php echo ($l['status'] ?? 'active') === 'active' ? 'bg-emerald-50 text-emerald-700 border border-emerald-200 hover:bg-emerald-100' : 'bg-slate-100 text-slate-500 hover:bg-slate-200'; ?>">
                                        <?php echo htmlspecialchars($l['status'] ?? 'active'); ?>
                                    </button>
                                </form>
                            </td>
                            <td class="py-3.5 px-4 text-right whitespace-nowrap">
                                <div class="flex items-center justify-end gap-1.5">
                                    <button type="button" onclick="editLanguage('<?php echo htmlspecialchars($l['code'], ENT_QUOTES); ?>', '<?php echo htmlspecialchars($l['name'], ENT_QUOTES); ?>', '<?php echo htmlspecialchars($l['native'] ?? '', ENT_QUOTES); ?>', '<?php echo htmlspecialchars($l['status'] ?? 'active', ENT_QUOTES); ?>')" class="p-1.5 text-purple-600 hover:bg-purple-50 rounded-lg text-xs font-semibold transition-colors" title="Edit Language">
                                        <i class="fa-solid fa-pen-to-square"></i>
                                    </button>
                                    <form method="POST" action="settings.php?tab=languages" class="inline-block" onsubmit="return confirm('Are you sure you want to delete language <?php echo htmlspecialchars($l['name'], ENT_QUOTES); ?>?');">
                                        <input type="hidden" name="action" value="delete_language">
                                        <input type="hidden" name="code" value="<?php echo htmlspecialchars($l['code']); ?>">
                                        <button type="submit" class="p-1.5 text-red-500 hover:bg-red-50 rounded-lg text-xs font-semibold transition-colors" title="Delete Language">
                                            <i class="fa-solid fa-trash"></i>
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
    <?php endif; ?>

    <?php if ($tab === 'security'): ?>
    <!-- Tab 4: Security, User Impersonation & Access Control -->
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        
        <!-- User Impersonation Tool -->
        <div class="bg-white rounded-3xl shadow-card border border-slate-100/90 p-6 sm:p-7 space-y-4">
            <div class="flex items-center gap-3">
                <div class="w-10 h-10 rounded-2xl bg-purple-50 text-purple-600 flex items-center justify-center font-bold text-lg">
                    <i class="fa-solid fa-user-secret"></i>
                </div>
                <div>
                    <h2 class="text-base font-bold text-slate-900">User Impersonation Tool</h2>
                    <p class="text-xs text-slate-400">Log in as any staff user to debug UI issues or verify permissions.</p>
                </div>
            </div>

            <div class="p-4 bg-amber-50 rounded-2xl border border-amber-200/80 text-xs text-amber-900">
                <i class="fa-solid fa-triangle-exclamation mr-1 text-amber-600"></i>
                <b>Developer Notice:</b> All impersonation actions are recorded into the security audit log. An amber top banner will allow you to return to SuperAdmin at any time.
            </div>

            <form method="POST" action="settings.php" class="space-y-4 pt-2">
                <input type="hidden" name="action" value="impersonate_user">

                <div>
                    <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">Select User Account to Impersonate</label>
                    <select name="target_user_id" required class="w-full px-4 py-2.5 bg-slate-50 border border-slate-200/80 rounded-2xl text-xs sm:text-sm font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-purple-500/20">
                        <?php foreach ($all_users as $u_item): 
                            if ($u_item['role'] === 'SuperAdmin') continue;
                        ?>
                            <option value="<?php echo $u_item['id']; ?>">
                                <?php echo htmlspecialchars($u_item['name'] . ' (' . $u_item['email'] . ') [' . $u_item['role'] . ']'); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <button type="submit" class="w-full py-3 bg-purple-600 hover:bg-purple-700 text-white font-bold text-xs sm:text-sm rounded-2xl transition-all shadow-sm shadow-purple-600/25">
                    <i class="fa-solid fa-right-to-bracket mr-1.5"></i> Impersonate Selected Account
                </button>
            </form>
        </div>

        <!-- Emergency Force Password Reset -->
        <div class="bg-white rounded-3xl shadow-card border border-slate-100/90 p-6 sm:p-7 space-y-4">
            <div class="flex items-center gap-3">
                <div class="w-10 h-10 rounded-2xl bg-red-50 text-red-600 flex items-center justify-center font-bold text-lg">
                    <i class="fa-solid fa-key"></i>
                </div>
                <div>
                    <h2 class="text-base font-bold text-slate-900">Emergency Password Reset</h2>
                    <p class="text-xs text-slate-400">Force reset password for any account (including Admin/Owner) if locked out.</p>
                </div>
            </div>

            <form method="POST" action="settings.php" class="space-y-4 pt-2">
                <input type="hidden" name="action" value="force_password_reset">

                <div>
                    <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">Target User</label>
                    <select name="target_user_id" required class="w-full px-4 py-2.5 bg-slate-50 border border-slate-200/80 rounded-2xl text-xs sm:text-sm font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-purple-500/20">
                        <?php foreach ($all_users as $u_item): ?>
                            <option value="<?php echo $u_item['id']; ?>">
                                <?php echo htmlspecialchars($u_item['name'] . ' (' . $u_item['email'] . ') [' . $u_item['role'] . ']'); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <div>
                    <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">New Password</label>
                    <input type="text" name="new_password" required value="password123" class="w-full px-4 py-2.5 bg-slate-50 border border-slate-200/80 rounded-2xl text-xs sm:text-sm font-mono text-slate-800 focus:outline-none focus:ring-2 focus:ring-purple-500/20">
                </div>

                <button type="submit" class="w-full py-3 bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs sm:text-sm rounded-2xl transition-all">
                    Force Set Password
                </button>
            </form>
        </div>

        <!-- Invalidate All Staff Sessions -->
        <div class="lg:col-span-2 bg-white rounded-3xl shadow-card border border-slate-100/90 p-6 sm:p-7 space-y-4">
            <div class="flex items-center justify-between">
                <div class="flex items-center gap-3">
                    <div class="w-10 h-10 rounded-2xl bg-amber-50 text-amber-600 flex items-center justify-center font-bold text-lg">
                        <i class="fa-solid fa-power-off"></i>
                    </div>
                    <div>
                        <h2 class="text-base font-bold text-slate-900">Kill All Active Staff Sessions</h2>
                        <p class="text-xs text-slate-400">Forces immediate logout for all logged-in staff and store accounts across all browsers.</p>
                    </div>
                </div>

                <form method="POST" action="settings.php" onsubmit="return confirm('Are you sure you want to invalidate all staff sessions? All users will be forced to log in again.');">
                    <input type="hidden" name="action" value="kill_sessions">
                    <button type="submit" class="px-5 py-2.5 rounded-2xl bg-amber-500 hover:bg-amber-600 text-white text-xs font-bold transition-all shadow-sm shadow-amber-500/20 flex items-center gap-2">
                        <i class="fa-solid fa-arrow-right-from-bracket"></i>
                        <span>Terminate All Staff Sessions</span>
                    </button>
                </form>
            </div>
        </div>

    </div>
    <?php endif; ?>

    <?php if ($tab === 'backups'): ?>
    <!-- Tab 5: Database & Backup Management -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        <!-- 1. Download Backup -->
        <div class="bg-white rounded-3xl shadow-card border border-slate-100/90 p-6 sm:p-7 space-y-4">
            <h2 class="text-base font-bold text-slate-900 flex items-center gap-2">
                <i class="fa-solid fa-database text-purple-600"></i> Database SQL Backup
            </h2>
            <p class="text-xs text-slate-400">Generate full SQL dump files containing all tables, schema, constraints, and data.</p>

            <div class="pt-2 space-y-3">
                <a href="settings.php?action=download_backup" class="w-full py-3 px-4 rounded-2xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs sm:text-sm transition-all shadow-sm shadow-blue-600/25 flex items-center justify-center gap-2">
                    <i class="fa-solid fa-download"></i>
                    <span>Download Complete SQL Backup (.sql)</span>
                </a>

                <form method="POST" action="settings.php">
                    <input type="hidden" name="action" value="purge_cache">
                    <button type="submit" class="w-full py-3 px-4 rounded-2xl border border-slate-200 text-slate-700 hover:bg-slate-50 font-bold text-xs sm:text-sm transition-colors flex items-center justify-center gap-2">
                        <i class="fa-solid fa-broom text-slate-400"></i>
                        <span>1-Click Purge System Caches</span>
                    </button>
                </form>
            </div>
        </div>

        <!-- 2. Restore Database -->
        <div class="bg-white rounded-3xl shadow-card border border-slate-100/90 p-6 sm:p-7 space-y-4">
            <h2 class="text-base font-bold text-slate-900 flex items-center gap-2">
                <i class="fa-solid fa-upload text-purple-600"></i> Restore Database (.sql)
            </h2>
            <p class="text-xs text-slate-400">Upload and execute any SQL dump file to restore system database tables and records.</p>

            <form method="POST" action="settings.php" enctype="multipart/form-data" class="space-y-3 pt-2" onsubmit="return confirm('⚠️ WARNING: Restoring an SQL backup may overwrite existing data. Are you sure you want to proceed?');">
                <input type="hidden" name="action" value="restore_backup">
                
                <div>
                    <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">Select .sql Backup File</label>
                    <input type="file" name="sql_file" accept=".sql" required class="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-700 file:mr-3 file:py-1.5 file:px-3 file:rounded-xl file:border-0 file:text-xs file:font-bold file:bg-purple-100 file:text-purple-700 hover:file:bg-purple-200">
                </div>

                <button type="submit" class="w-full py-3 px-4 rounded-2xl bg-purple-600 hover:bg-purple-700 text-white font-bold text-xs sm:text-sm transition-all shadow-sm shadow-purple-600/25 flex items-center justify-center gap-2">
                    <i class="fa-solid fa-cloud-arrow-up"></i>
                    <span>Execute Database Restore</span>
                </button>
            </form>
        </div>

        <!-- 3. Migration Runner -->
        <div class="bg-white rounded-3xl shadow-card border border-slate-100/90 p-6 sm:p-7 space-y-4">
            <h2 class="text-base font-bold text-slate-900 flex items-center gap-2">
                <i class="fa-solid fa-screwdriver-wrench text-purple-600"></i> Schema Health & Migration
            </h2>
            <p class="text-xs text-slate-400">Execute automatic schema migration scripts to ensure all columns, tables, and foreign keys are synchronised.</p>

            <form method="POST" action="settings.php" class="pt-2">
                <input type="hidden" name="action" value="run_migration">
                <button type="submit" class="w-full py-3 px-4 rounded-2xl bg-emerald-500 hover:bg-emerald-600 text-white font-bold text-xs sm:text-sm transition-all shadow-sm shadow-emerald-500/25 flex items-center justify-center gap-2">
                    <i class="fa-solid fa-arrows-rotate"></i>
                    <span>Run Schema Self-Repair</span>
                </button>
            </form>
        </div>

    </div>
    <?php endif; ?>

    <?php if ($tab === 'diagnostics'): ?>
    <!-- Tab 6: Diagnostics & Logs -->
    <div class="space-y-6">
        
        <div class="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <div class="bg-white rounded-3xl p-5 shadow-card border border-slate-100/90">
                <span class="text-xs font-bold text-slate-400 block uppercase">PHP Version</span>
                <span class="text-lg font-black text-slate-900 mt-1 block"><?php echo phpversion(); ?></span>
            </div>

            <div class="bg-white rounded-3xl p-5 shadow-card border border-slate-100/90">
                <span class="text-xs font-bold text-slate-400 block uppercase">Memory Limit</span>
                <span class="text-lg font-black text-slate-900 mt-1 block"><?php echo ini_get('memory_limit'); ?></span>
            </div>

            <div class="bg-white rounded-3xl p-5 shadow-card border border-slate-100/90">
                <span class="text-xs font-bold text-slate-400 block uppercase">Max Execution Time</span>
                <span class="text-lg font-black text-slate-900 mt-1 block"><?php echo ini_get('max_execution_time'); ?>s</span>
            </div>

            <div class="bg-white rounded-3xl p-5 shadow-card border border-slate-100/90">
                <span class="text-xs font-bold text-slate-400 block uppercase">Server OS</span>
                <span class="text-lg font-black text-slate-900 mt-1 block"><?php echo PHP_OS_FAMILY; ?></span>
            </div>
        </div>

        <div class="bg-white rounded-3xl shadow-card border border-slate-100/90 p-6 sm:p-7 space-y-4">
            <div class="flex items-center justify-between">
                <h2 class="text-base font-bold text-slate-900 flex items-center gap-2">
                    <i class="fa-solid fa-terminal text-purple-600"></i> Live Activity & Error Diagnostics
                </h2>

                <form method="POST" action="settings.php?tab=diagnostics" onsubmit="return confirm('Are you sure you want to clear all activity and audit logs?');">
                    <input type="hidden" name="action" value="clear_logs">
                    <button type="submit" class="px-4 py-2 bg-red-50 hover:bg-red-100 text-red-600 rounded-xl text-xs font-bold transition-colors flex items-center gap-1.5">
                        <i class="fa-solid fa-trash-can"></i>
                        <span>Clear All Logs</span>
                    </button>
                </form>
            </div>
            
            <div class="p-4 bg-slate-900 text-slate-200 rounded-2xl font-mono text-xs overflow-x-auto space-y-1.5 max-h-80 overflow-y-auto">
                <div class="text-emerald-400 font-bold">[<?php echo date('Y-m-d H:i:s'); ?>] [SYSTEM HEALTHY] Database connection verified (MySQL PDO Active).</div>
                <div class="text-slate-400">[<?php echo date('Y-m-d H:i:s'); ?>] [SESSION] SuperAdmin active authenticated session ID: <?php echo session_id(); ?></div>
                <div class="text-slate-400">[<?php echo date('Y-m-d H:i:s'); ?>] [CURRENCY MASTER] <?php echo count($system_currencies); ?> active currency definitions loaded.</div>
                <div class="text-slate-400">[<?php echo date('Y-m-d H:i:s'); ?>] [LANGUAGE MASTER] <?php echo count($system_languages); ?> active language definitions loaded.</div>
                <?php
                if ($pdo) {
                    try {
                        $logs = $pdo->query("SELECT a.*, u.name as user_name FROM activity_logs a LEFT JOIN users u ON a.user_id = u.id ORDER BY a.id DESC LIMIT 20")->fetchAll(PDO::FETCH_ASSOC);
                        foreach ($logs as $l) {
                            echo '<div class="text-purple-300">[' . htmlspecialchars($l['created_at'] ?? date('Y-m-d H:i:s')) . '] [' . htmlspecialchars($l['module'] ?? 'System') . '] ' . htmlspecialchars($l['user_name'] ?? 'System') . ': ' . htmlspecialchars($l['details'] ?? $l['action'] ?? '') . '</div>';
                        }
                    } catch (Exception $ex) {}
                }
                ?>
            </div>
        </div>

    </div>
    <?php endif; ?>

</div>

<!-- Floating Real-Time Toast Notification -->
<div id="liveToast" class="fixed bottom-6 right-6 z-[9999] hidden flex items-center gap-3 px-5 py-3.5 bg-slate-900 text-white rounded-2xl shadow-2xl border border-slate-700/80 text-xs font-bold transition-all duration-300 transform translate-y-2">
    <div id="toastIcon" class="w-6 h-6 rounded-full bg-emerald-500/20 text-emerald-400 flex items-center justify-center text-xs">
        <i class="fa-solid fa-check"></i>
    </div>
    <span id="toastMsg">Updated instantly</span>
</div>

<script>
function editCurrency(code, name, symbol, rate, status) {
    const form = document.querySelector('form[action*="tab=currencies"]');
    if (form) {
        form.querySelector('input[name="code"]').value = code;
        form.querySelector('input[name="name"]').value = name;
        form.querySelector('input[name="symbol"]').value = symbol;
        form.querySelector('input[name="rate"]').value = rate;
        form.querySelector('select[name="status"]').value = status;
        form.scrollIntoView({ behavior: 'smooth' });
        showToast('Loaded ' + code + ' into form for editing', 'success');
    }
}

function editLanguage(code, name, native, status) {
    document.getElementById('langCodeInput').value = code;
    document.getElementById('langNameInput').value = name;
    document.getElementById('langNativeInput').value = native;
    document.getElementById('langStatusInput').value = status;
    document.getElementById('langForm').scrollIntoView({ behavior: 'smooth' });
    showToast('Loaded ' + name + ' into form for editing', 'success');
}
let toastTimer = null;
function showToast(msg, type = 'success') {
    const toast = document.getElementById('liveToast');
    const toastMsg = document.getElementById('toastMsg');
    const toastIcon = document.getElementById('toastIcon');
    if (!toast || !toastMsg) return;

    toastMsg.textContent = msg;
    if (type === 'error') {
        toastIcon.className = 'w-6 h-6 rounded-full bg-red-500/20 text-red-400 flex items-center justify-center text-xs';
        toastIcon.innerHTML = '<i class="fa-solid fa-circle-exclamation"></i>';
    } else {
        toastIcon.className = 'w-6 h-6 rounded-full bg-emerald-500/20 text-emerald-400 flex items-center justify-center text-xs';
        toastIcon.innerHTML = '<i class="fa-solid fa-bolt"></i>';
    }

    toast.classList.remove('hidden', 'translate-y-2');
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => {
        toast.classList.add('hidden', 'translate-y-2');
    }, 2800);
}

function quickLiveToggle(key, isChecked, checkboxEl, badgeId = null, onText = '', offText = '') {
    const value = isChecked ? '1' : '0';
    
    // Update badge visual immediately
    if (badgeId) {
        const badge = document.getElementById(badgeId);
        if (badge) {
            badge.textContent = isChecked ? onText : offText;
            if (key === 'maintenance_mode') {
                badge.className = isChecked ? 'px-2 py-0.5 rounded-full text-[10px] font-extrabold uppercase bg-purple-200 text-purple-800 animate-pulse' : 'px-2 py-0.5 rounded-full text-[10px] font-extrabold uppercase bg-slate-200 text-slate-600';
            } else if (key === 'shop_disabled') {
                badge.className = isChecked ? 'px-2 py-0.5 rounded-full text-[10px] font-extrabold uppercase bg-red-200 text-red-800 animate-pulse' : 'px-2 py-0.5 rounded-full text-[10px] font-extrabold uppercase bg-emerald-100 text-emerald-800';
            }
        }
    }

    fetch('api_status.php', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ key: key, value: value })
    })
    .then(r => r.json())
    .then(data => {
        if (data.success) {
            showToast(data.message || (key + ' updated live!'), 'success');
        } else {
            showToast('Error: ' + (data.error || 'Failed to update'), 'error');
            checkboxEl.checked = !isChecked; // revert
        }
    })
    .catch(err => {
        showToast('Network error updating setting.', 'error');
        checkboxEl.checked = !isChecked; // revert
    });
}

function quickLiveTextUpdate(key, inputEl) {
    const value = inputEl.value;
    fetch('api_status.php', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ key: key, value: value })
    })
    .then(r => r.json())
    .then(data => {
        if (data.success) {
            showToast('⚡ Notice message updated in real-time!', 'success');
        }
    })
    .catch(() => {
        showToast('Network error updating notice message.', 'error');
    });
}
</script>

<?php require_once '../includes/footer.php'; ?>
